### Products Index
GET http://localhost:3000/products 

### Products Create
POST http://localhost:3000/products
Content-Type: application/json 

{
  "name": "test test"
}

### Products Show
GET http://localhost:3000/products/1

### Products Update
PATCH http://localhost:3000/products/8 
Content-Type: application/json 

{
  "name": "update name",
  "price": 1000,
  "image_url": "test image",
  "description": "update description"
}

### Products Destroy
DELETE http://localhost:3000/products/8